name: "RoTransNet_MSBrain_128"
backend: "onnxruntime"

max_batch_size: 24

dynamic_batching {
    preferred_batch_size: [ 24 ]
    max_queue_delay_microseconds: 100
}

input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 1, 128, 128 ]
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 9, 128, 128 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
    gpus: [ 0 ]
  }
]

optimization {
    execution_accelerators {
        gpu_execution_accelerator: [
        {
            name: "tensorrt"
            parameters {
                key: "precision_mode"
                value: "FP32"
            }
            parameters {
                key: "max_workspace_size_bytes"
                value: "4294967296"
            }
            parameters {
                key: "trt_engine_cache_enable"
                value: "true"
            }
            parameters {
                key: "trt_engine_cache_path"
                value: "/models/RoTransNet_MSBrain_128/1"
            }
        }
        ]
    }
}